### ISSUE TITLE
Buffer overflow reading field.

### ISSUE THREAD

**Issue by tnyamaguchi** [auerlab/vcf-split#7]
Hi, 

I used the main branch and got this message.

`dsv_read_field(): Buffer overflow reading field.`
`Buffer size = 33`

It looks like the alt column can not contain more than 33 characters?

Thank you

**Comment by outpaddling** [comment]
33 is the size of the ALT field buffer, which is normally only 1 character.  Either there's something odd in that column or the VCF read got out of phase due to something odd in one of the lines before it.  Make sure all your ALT values are sensible and that all lines have the correct number of columns.
Also, how did you install vcf-split?  If it is not using the correct version of libxtend and biolibc, all bets are off.  Installing via FreeBSD ports or pkgsrc will ensure this.

**Comment by tnyamaguchi** [comment]
Thanks for the quick response. 

>which is normally only 1 character. 

Right, but the VCF input contains indel entries like `GTTTTTTT,GT,GTTTTTTTT,GTTTTTTTTGT`.

>how did you install vcf-split?

We used `pkgsrc`

**Comment by outpaddling** [comment]
Sorry for the delay, I never got a notification email about your reply.

Send me the output of 

awk '{ print length($5); }' file.vcf | sort -u | tail

so we know what the largest ALT field is.  I may want to dynamically allocate this if it's highly variable, but that would entail a small performance penalty.

**Comment by outpaddling** [comment]
I updated biolibc to dynamically allocate the alt field.  To test, try the following:

1. Check out pkgsrc-wip if you have not already (install sysutils/suto-admin and run auto-pkgsrc-wip-checkout)
2. pkg_delete -rR biolibc
3. auto-update-pkgsrc --defaults
4. cd pkgsrc-dir/wip/vcf-split
5. sbmake install

**Comment by outpaddling** [comment]
Closing due to feedback timeout.  Feel free to reopen if this is still an issue.
